// src/pages/Home/mockData.js
export const MOCK_EMAILS = [
  { id: "all", label: "전체", count: 18 },
  {
    id: "gmail",
    label: "minji.kim@gmail.com",
    groupLabel: "Gmail동",
    count: 13,
    avatarBg: "#3b6cff",
    avatarLabel: "M",
    isPrimary: true,
  },
  {
    id: "work",
    label: "minji.work@gmail.com",
    groupLabel: "업무동",
    count: 5,
    avatarBg: "#3b6cff",
    avatarLabel: "W",
  },
];

// id: 계정 고유 식별자 (서버의 serviceAccountId에 해당, 절대 겹치지 않음)
// service: 서비스 종류 (아이콘/이름/상세 데이터 조회용 - 여러 계정이 같은 service를 가질 수 있음)
export const MOCK_ACCOUNTS = [
  {
    id: "acc_disney_gmail",
    service: "disney",
    name: "Disney+",
    emailGroup: "gmail",
    status: "risk",
    iconBg: "linear-gradient(160deg,#0a2fa8,#0063e5)",
    iconText: "D+",
    reason: "새 기기 로그인 · 결제 계정 · 위험도 높음",
  },
  {
    id: "acc_adobe_gmail",
    service: "adobe",
    name: "Adobe CC",
    emailGroup: "gmail",
    status: "risk",
    iconBg: "linear-gradient(160deg,#c00000,#ff0000)",
    iconText: "Cc",
  },
  {
    id: "acc_netflix_gmail",
    service: "netflix",
    name: "Netflix",
    emailGroup: "gmail",
    status: "leak",
    iconBg: "linear-gradient(160deg,#8b0000,#e50914)",
    iconText: "N",
  },
  {
    id: "acc_youtube_gmail",
    service: "youtube",
    name: "YouTube",
    emailGroup: "gmail",
    status: "safe",
    iconBg: "linear-gradient(160deg,#c00000,#ff0000)",
    iconText: "▶",
  },
  {
    id: "acc_google_gmail",
    service: "google",
    name: "Google",
    emailGroup: "gmail",
    status: "safe",
    iconBg: "linear-gradient(160deg,#5488f3,#4285f4)",
    iconText: "G",
  },
  {
    id: "acc_coupang_gmail",
    service: "coupang",
    name: "Coupang",
    emailGroup: "gmail",
    status: "safe",
    iconBg: "linear-gradient(160deg,#ff6040,#e04e39)",
    iconText: "쿠팡",
  },
  {
    id: "acc_naver_gmail",
    service: "naver",
    name: "Naver",
    emailGroup: "gmail",
    status: "safe",
    iconBg: "linear-gradient(160deg,#04d85e,#03c75a)",
    iconText: "N",
  },
  {
    id: "acc_spotify_gmail",
    service: "spotify",
    name: "Spotify",
    emailGroup: "gmail",
    status: "safe",
    iconBg: "linear-gradient(160deg,#21d25a,#1db954)",
    iconText: "S",
  },
  {
    id: "acc_chatgpt_gmail",
    service: "chatgpt",
    name: "ChatGPT",
    emailGroup: "gmail",
    status: "safe",
    iconBg: "linear-gradient(160deg,#0da87c,#0d9488)",
    iconText: "GPT",
  },
  {
    id: "acc_watcha_gmail",
    service: "watcha",
    name: "Watcha",
    emailGroup: "gmail",
    status: "dormant",
    iconBg: "#c8d3de",
    iconText: "W",
  },
  {
    id: "acc_melon_gmail",
    service: "melon",
    name: "Melon",
    emailGroup: "gmail",
    status: "dormant",
    iconBg: "#c8d3de",
    iconText: "M",
  },
  {
    id: "acc_figma_gmail",
    service: "figma",
    name: "Figma",
    emailGroup: "gmail",
    status: "dormant",
    iconBg: "#c8d3de",
    iconText: "Fg",
  },

  {
    id: "acc_slack_work",
    service: "slack",
    name: "Slack",
    emailGroup: "work",
    status: "safe",
    iconBg: "linear-gradient(160deg,#4a154b,#7c3085)",
    iconText: "Sl",
  },
  {
    id: "acc_notion_work",
    service: "notion",
    name: "Notion",
    emailGroup: "work",
    status: "safe",
    iconBg: "linear-gradient(160deg,#1a1a1a,#373737)",
    iconText: "N",
  },
  {
    id: "acc_figma_work",
    service: "figma",
    name: "Figma",
    emailGroup: "work",
    status: "safe",
    iconBg: "linear-gradient(160deg,#1e1e1e,#f24e1e)",
    iconText: "Fg",
  },
  {
    id: "acc_zoom_work",
    service: "zoom",
    name: "Zoom",
    emailGroup: "work",
    status: "safe",
    iconBg: "linear-gradient(160deg,#0e72ed,#2d8cff)",
    iconText: "Zoom",
  },
  {
    id: "acc_github_work",
    service: "github",
    name: "GitHub",
    emailGroup: "work",
    status: "safe",
    iconBg: "linear-gradient(160deg,#1b1f23,#3d444c)",
    iconText: "GH",
  },
];
